"""Configuration for the MCP server, including constants and browser page settings."""

# DO NOT EDIT THIS FILE DIRECTLY. Instead, copy this to config_site.py and customize for your site.

try:
    from .config_site import (
        API_BASE,
        BROWSER_PAGE_CONFIG,
        DATASTORE_DESCRIPTION,
        DATASTORE_FULL_DESCRIPTION,
        DATASTORE_FULL_NAME,
        DATASTORE_NAME,
        ISSUE_TEMPLATE_UNHANDLED_ERROR,
        ISSUE_URL,
        LOGO_FILE,
        MCP_DESCRIPTION,
        SITE_NAME,
        USER_AGENT,
        WEB_URL,
    )
except ImportError:
    # Fallback to example config if custom config is not provided
    from .config_example import (
        API_BASE,
        BROWSER_PAGE_CONFIG,
        DATASTORE_DESCRIPTION,
        DATASTORE_FULL_DESCRIPTION,
        DATASTORE_FULL_NAME,
        DATASTORE_NAME,
        ISSUE_TEMPLATE_UNHANDLED_ERROR,
        ISSUE_URL,
        LOGO_FILE,
        MCP_DESCRIPTION,
        SITE_NAME,
        USER_AGENT,
        WEB_URL,
    )

# export constants for use in other modules
__all__ = (
    "DATASTORE_DESCRIPTION",
    "DATASTORE_FULL_NAME",
    "DATASTORE_FULL_DESCRIPTION",
    "DATASTORE_NAME",
    "MCP_DESCRIPTION",
    "WEB_URL",
    "API_BASE",
    "ISSUE_URL",
    "ISSUE_TEMPLATE_UNHANDLED_ERROR",
    "LOGO_FILE",
    "SITE_NAME",
    "USER_AGENT",
    "BROWSER_PAGE_CONFIG",
)
